/**
 * TicTacToe API
 * TicTacToe API documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hlavjah@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


/**
 * The Game entity. @author hlavja
 */
export interface GameDTO { 
    created?: Date;
    firstPlayerId?: number;
    firstPlayerLogin?: string;
    gameStatus?: string;
    gameType?: string;
    id?: number;
    result?: string;
    secondPlayerId?: number;
    secondPlayerLogin?: string;
    turnUserId?: number;
    turnUserLogin?: string;
    winningPlayerId?: number;
    winningPlayerLogin?: string;
}
