/**
 * TicTacToe API
 * TicTacToe API documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hlavjah@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface PlayerDTO { 
    available?: boolean;
    friend?: boolean;
    login?: string;
    online?: boolean;
    playerId?: number;
}
