export * from './accountResource.service';
import { AccountResourceService } from './accountResource.service';
export * from './friendResource.service';
import { FriendResourceService } from './friendResource.service';
export * from './gameResource.service';
import { GameResourceService } from './gameResource.service';
export * from './lobbyResource.service';
import { LobbyResourceService } from './lobbyResource.service';
export * from './moveResource.service';
import { MoveResourceService } from './moveResource.service';
export * from './userJwtController.service';
import { UserJwtControllerService } from './userJwtController.service';
export * from './userResource.service';
import { UserResourceService } from './userResource.service';
export const APIS = [AccountResourceService, FriendResourceService, GameResourceService, LobbyResourceService, MoveResourceService, UserJwtControllerService, UserResourceService];
