/**
 * TicTacToe API
 * TicTacToe API documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: hlavjah@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { FriendDTO } from '../model/friendDTO';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class FriendResourceService {

    protected basePath = 'https://localhost:8080/api';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * addFriend
     * 
     * @param addFriendLogin addFriendLogin
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public addFriendUsingPOST(addFriendLogin: string, observe?: 'body', reportProgress?: boolean): Observable<FriendDTO>;
    public addFriendUsingPOST(addFriendLogin: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<FriendDTO>>;
    public addFriendUsingPOST(addFriendLogin: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<FriendDTO>>;
    public addFriendUsingPOST(addFriendLogin: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (addFriendLogin === null || addFriendLogin === undefined) {
            throw new Error('Required parameter addFriendLogin was null or undefined when calling addFriendUsingPOST.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (addFriendLogin !== undefined && addFriendLogin !== null) {
            queryParameters = queryParameters.set('addFriendLogin', <any>addFriendLogin);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];

        return this.httpClient.post<FriendDTO>(`${this.basePath}/friends/add-friend`,
            null,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * removeFriend
     * 
     * @param friendId friendId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public removeFriendUsingDELETE(friendId: number, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public removeFriendUsingDELETE(friendId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public removeFriendUsingDELETE(friendId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public removeFriendUsingDELETE(friendId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (friendId === null || friendId === undefined) {
            throw new Error('Required parameter friendId was null or undefined when calling removeFriendUsingDELETE.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (friendId !== undefined && friendId !== null) {
            queryParameters = queryParameters.set('friendId', <any>friendId);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<any>(`${this.basePath}/friends/remove-friend`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
